In [1]:
import warnings

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, r2_score

In [2]:
df = pd.read_csv('weatherAUS.csv')
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

## Q1 Preprocess the data, remove the attributes which were are not useful to predict rain. Also, remove rows with at least one missing value for each of them.

In [3]:
df.isna().sum() #checking for null values

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [4]:
df.drop('Date', axis=1, inplace=True) #dropping date column which is not useful

In [5]:
df.dropna(inplace=True) #dropping all rows with null values

In [6]:
df.shape

(56420, 22)

In [7]:
target = df.pop('RainTomorrow')
df

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
6049,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0,ENE,SW,...,20.0,20.0,13.0,1006.3,1004.4,2.0,5.0,26.6,33.4,No
6050,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0,SSE,SSE,...,19.0,30.0,8.0,1012.9,1012.1,1.0,1.0,20.3,27.0,No
6052,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0,NNE,NNW,...,15.0,42.0,22.0,1012.3,1009.2,1.0,6.0,28.7,34.9,No
6053,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0,WNW,WSW,...,6.0,37.0,22.0,1012.7,1009.1,1.0,5.0,29.1,35.6,No
6054,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0,NW,WNW,...,13.0,19.0,15.0,1010.7,1007.4,1.0,6.0,33.6,37.6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0,SE,NE,...,20.0,63.0,32.0,1013.9,1010.5,0.0,1.0,24.5,32.3,No
142299,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0,SE,SE,...,11.0,56.0,28.0,1014.6,1011.2,7.0,0.0,24.8,32.0,No
142300,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0,E,W,...,11.0,46.0,23.0,1015.3,1011.8,0.0,0.0,24.8,32.1,No
142301,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0,SE,NNW,...,17.0,62.0,58.0,1014.9,1010.7,1.0,1.0,24.8,29.2,No
142302,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0,ENE,NNW,...,7.0,73.0,32.0,1013.9,1009.7,6.0,5.0,25.4,31.0,No

In [8]:
#map 0 to 'no' and 1 to 'yes'
mapyn = {'No': 0, 'Yes': 1}
target = target.map(mapyn)

## Q2 Calculate  the  Variance  Inflation  Factor  (VIF)  value.  VIF  is  a  number  that determines whether a variable has multicollinearity or not (starts from 1, and it has  no  upper  limit.  If  the  number  gets  larger,  it  means  the variable  has  huge multicollinearity on it.).

In [9]:
numerical_cols   = [c for c in df.columns if df[c].dtype in ['int64', 'float64']] # for numerical columns
categorical_cols = [c for c in df.columns if df[c].dtype == 'object'] # for categorical columns

df_num = df[numerical_cols]
df_cat = df[categorical_cols]

In [10]:
#calculating the R2 scores from linear regression
linreg = LinearRegression()
vif = {}
for col in numerical_cols:
    all_cols = list(numerical_cols)
    all_cols.remove(col)
    x = df_num[all_cols]
    y = df_num[col]
    linreg.fit(x, y)
    y_pred = linreg.predict(x)
    score = r2_score(y, y_pred)
    vif[col] = 1 / (1 - score)
    
vif

{'MinTemp': 10.770219691409906,
 'MaxTemp': 46.78406795924843,
 'Rainfall': 1.1779953082896786,
 'Evaporation': 2.224815286348291,
 'Sunshine': 3.3077307556062605,
 'WindGustSpeed': 2.878864348472314,
 'WindSpeed9am': 1.856489347720245,
 'WindSpeed3pm': 2.1463942950501775,
 'Humidity9am': 4.417547175413456,
 'Humidity3pm': 6.803333309913033,
 'Pressure9am': 19.876241743158516,
 'Pressure3pm': 19.86913652734502,
 'Cloud9am': 2.2382633768389075,
 'Cloud3pm': 2.2774283640218864,
 'Temp9am': 24.36887019910182,
 'Temp3pm': 56.08268800345098}

## Q4 Remove features that have a VIF valueabove 5.

In [11]:
#dropping columns where vif > 5
drop_cols = [key for key in vif.keys() if vif[key] > 5]
drop_cols

['MinTemp',
 'MaxTemp',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Temp9am',
 'Temp3pm']

In [12]:
df_num.drop(drop_cols, axis=1, inplace=True)

/tmp/ipykernel_9314/4175395141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_num.drop(drop_cols, axis=1, inplace=True)

## Q3 Remove multicollinearities by creating new features. Find the features that have paired values and create the new feature which is the difference value between those pairs.

In [13]:
df_num.corr()

,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Cloud9am,Cloud3pm
Rainfall,1.000000,-0.077239,-0.246379,0.106308,0.050584,0.044112,0.263625,0.217169,0.191433
Evaporation,-0.077239,1.000000,0.369250,0.209566,0.193154,0.124345,-0.554232,-0.199809,-0.202366
Sunshine,-0.246379,0.369250,1.000000,-0.052422,-0.013842,0.029200,-0.500343,-0.677939,-0.702022
WindGustSpeed,0.106308,0.209566,-0.052422,1.000000,0.608852,0.685236,-0.193410,0.088129,0.131590
WindSpeed9am,0.050584,0.193154,-0.013842,0.608852,1.000000,0.502226,-0.236795,0.034908,0.062507
WindSpeed3pm,0.044112,0.124345,0.029200,0.685236,0.502226,1.000000,-0.100626,0.068224,0.041475
Humidity9am,0.263625,-0.554232,-0.500343,-0.193410,-0.236795,-0.100626,1.000000,0.438962,0.348707
Cloud9am,0.217169,-0.199809,-0.677939,0.088129,0.034908,0.068224,0.438962,1.000000,0.614380
Cloud3pm,0.191433,-0.202366,-0.702022,0.131590,0.062507,0.041475,0.348707,0.614380,1.000000

### From the above correlation matrix, we can see that the groups of variables with correlation more than 0.6 are:

* WindGustSpeed, WindSpeed3pm
* WindGustSpeed, WindSpeed9am
* Cloud9am, Cloud3pm

In [14]:
#removing all columns with high multicollinearity
numerical_cols = list(numerical_cols)
numerical_cols.remove('Cloud9am')
numerical_cols.remove('Cloud3pm')
numerical_cols.remove('WindGustSpeed')
numerical_cols.remove('WindSpeed3pm')
numerical_cols.remove('WindSpeed9am')

In [15]:
#creating new columns
df_num = df[numerical_cols]
df_num['Cloud9am - Cloud3pm'] = df['Cloud9am'] - df['Cloud3pm']
df_num['WindGustSpeed - WindSpeed3pm'] = df['WindGustSpeed'] - df['WindSpeed3pm']
df_num['WindGustSpeed - WindSpeed9am'] = df['WindGustSpeed'] - df['WindSpeed9am']
df_num.head()

/tmp/ipykernel_9314/1728966887.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_num['Cloud9am - Cloud3pm'] = df['Cloud9am'] - df['Cloud3pm']
/tmp/ipykernel_9314/1728966887.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_num['WindGustSpeed - WindSpeed3pm'] = df['WindGustSpeed'] - df['WindSpeed3pm']
/tmp/ipykernel_9314/1728966887.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_num['WindGustSpeed - WindSpeed9am'] = df['WindGustSpeed'] - df['WindSpeed9am']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,Cloud9am - Cloud3pm,WindGustSpeed - WindSpeed3pm,WindGustSpeed - WindSpeed9am
6049,17.9,35.2,0.0,12.0,12.3,20.0,13.0,1006.3,1004.4,26.6,33.4,-3.0,28.0,42.0
6050,18.4,28.9,0.0,14.8,13.0,30.0,8.0,1012.9,1012.1,20.3,27.0,0.0,18.0,18.0
6052,19.4,37.6,0.0,10.8,10.6,42.0,22.0,1012.3,1009.2,28.7,34.9,-5.0,31.0,16.0
6053,21.9,38.4,0.0,11.4,12.2,37.0,22.0,1012.7,1009.1,29.1,35.6,-4.0,25.0,25.0
6054,24.2,41.0,0.0,11.2,8.4,19.0,15.0,1010.7,1007.4,33.6,37.6,-5.0,22.0,18.0

In [16]:
temp_df = pd.merge(df_num, df_cat, left_index = True, right_index = True)
temp_df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,Cloud9am - Cloud3pm,WindGustSpeed - WindSpeed3pm,WindGustSpeed - WindSpeed9am,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday
6049,17.9,35.2,0.0,12.0,12.3,20.0,13.0,1006.3,1004.4,26.6,33.4,-3.0,28.0,42.0,Cobar,SSW,ENE,SW,No
6050,18.4,28.9,0.0,14.8,13.0,30.0,8.0,1012.9,1012.1,20.3,27.0,0.0,18.0,18.0,Cobar,S,SSE,SSE,No
6052,19.4,37.6,0.0,10.8,10.6,42.0,22.0,1012.3,1009.2,28.7,34.9,-5.0,31.0,16.0,Cobar,NNE,NNE,NNW,No
6053,21.9,38.4,0.0,11.4,12.2,37.0,22.0,1012.7,1009.1,29.1,35.6,-4.0,25.0,25.0,Cobar,WNW,WNW,WSW,No
6054,24.2,41.0,0.0,11.2,8.4,19.0,15.0,1010.7,1007.4,33.6,37.6,-5.0,22.0,18.0,Cobar,WNW,NW,WNW,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,19.3,33.4,0.0,6.0,11.0,63.0,32.0,1013.9,1010.5,24.5,32.3,-1.0,15.0,26.0,Darwin,ENE,SE,NE,No
142299,21.2,32.6,0.0,7.6,8.6,56.0,28.0,1014.6,1011.2,24.8,32.0,7.0,26.0,24.0,Darwin,E,SE,SE,No
142300,20.7,32.8,0.0,5.6,11.0,46.0,23.0,1015.3,1011.8,24.8,32.1,0.0,22.0,16.0,Darwin,E,E,W,No
142301,19.5,31.8,0.0,6.2,10.6,62.0,58.0,1014.9,1010.7,24.8,29.2,0.0,9.0,17.0,Darwin,ESE,SE,NNW,No
142302,20.2,31.7,0.0,5.6,10.7,73.0,32.0,1013.9,1009.7,25.4,31.0,1.0,23.0,15.0,Darwin,ENE,ENE,NNW,No

## Q5 Build a regression model to perform the Rain prediction. Also, tabulate accuracy of the prediction models, before and VIF computation.

In [17]:
#encoding all categorical columns
df_new = pd.get_dummies(temp_df)
df_new

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,...,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_No,RainToday_Yes
6049,17.9,35.2,0.0,12.0,12.3,20.0,13.0,1006.3,1004.4,26.6,...,0,0,0,0,1,0,0,0,1,0
6050,18.4,28.9,0.0,14.8,13.0,30.0,8.0,1012.9,1012.1,20.3,...,0,0,1,0,0,0,0,0,1,0
6052,19.4,37.6,0.0,10.8,10.6,42.0,22.0,1012.3,1009.2,28.7,...,0,0,0,0,0,0,0,0,1,0
6053,21.9,38.4,0.0,11.4,12.2,37.0,22.0,1012.7,1009.1,29.1,...,0,0,0,0,0,0,0,1,1,0
6054,24.2,41.0,0.0,11.2,8.4,19.0,15.0,1010.7,1007.4,33.6,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142298,19.3,33.4,0.0,6.0,11.0,63.0,32.0,1013.9,1010.5,24.5,...,0,0,0,0,0,0,0,0,1,0
142299,21.2,32.6,0.0,7.6,8.6,56.0,28.0,1014.6,1011.2,24.8,...,0,1,0,0,0,0,0,0,1,0
142300,20.7,32.8,0.0,5.6,11.0,46.0,23.0,1015.3,1011.8,24.8,...,0,0,0,0,0,1,0,0,1,0
142301,19.5,31.8,0.0,6.2,10.6,62.0,58.0,1014.9,1010.7,24.8,...,0,0,0,0,0,0,0,0,1,0
142302,20.2,31.7,0.0,5.6,10.7,73.0,32.0,1013.9,1009.7,25.4,...,0,0,0,0,0,0,0,0,1,0

In [18]:
#converting all values to same Datatype
df_new = df_new.astype('float64')
target = target.astype('float64')

In [19]:
x_train, x_test, y_train, y_test = train_test_split(df_new, target, test_size = 0.3, random_state = 173)

In [20]:
model = LogisticRegression(random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

/home/arch/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0., 0., 0., ..., 0., 1., 1.])

In [21]:
accuracy_score(y_test, y_pred)

0.8505258182677538